apiVersion: apps/v1
kind: Deployment
metadata:
  name: lettuce
  annotations:
    greymatter.io/configure-sidecar: "false"
spec:
  selector:
    matchLabels:
      app: lettuce
  template:
    metadata:
      labels:
        app: lettuce
    spec:
      containers:
        - name: lettuce
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "42071"]
          ports:
          - name: ingress
            containerPort: 42071
